# Generated by Django 4.1.7 on 2023-03-16 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_zapato'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ropa',
            new_name='Camiseta',
        ),
    ]
